### ISSUE TITLE
YOLO cpp for windows dev env ( Visual Studio 2015 C++)

### ISSUE THREAD

**Issue by bassamarshad** [for-aiur/yolo_cpp#2]
Great effort for this C++ port for GCC env. 

I am not sure how much porting would be required on this code, for a windows env (VS 2015 etc). 

Let me know if anyone is aware of such a repository for YOLOv2 in C++ and Windows & Visual Studio.

**Comment by for-aiur** [comment]
I am trying to generate a vs2013 solution file using cmake-gui for windows and compile the code via vs2013. I will let you know.

**Comment by bassamarshad** [comment]
Bravo ! Keep us posted.

**Comment by bassamarshad** [comment]
Any luck with the C++ windows/Visual Studio compatible version.

**Comment by sqyangg** [comment]
Hi, I'm also searching for C++/Visual Studio version, do you have any good news or suggestion? Thank you

**Comment by bassamarshad** [comment]
Here you go man : https://github.com/AlexeyAB/darknet/issues/27
